replicaCount: 1

image:
  repository: prom/prometheus
  tag: latest

service:
  name: prometheus
  type: ClusterIP
  port: 9090

resources: {}

config:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
