apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-gm-access-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/gm-access/*.log
      pos_file /fluentd/log/gm-access.pos
      tag gm-access.log
      <parse>
        @type none
      </parse>
    </source>

    <match gm-access.log>
      @type stdout  # Replace this with your preferred output plugin
      @log_level info
    </match>

#Create this config on node using
#  kubectl apply -f fluentd-gm-user-config.yaml
