apiVersion: v1
kind: Service
metadata:
  name: gm-access-service
spec:
  type: ClusterIP  # Change from ClusterIP to NodePort
  selector:
    app: gm-access-service
  ports:
    - protocol: TCP
      port: {{ .Values.services.gmAccess.containerPort }}         # The service port inside the cluster
      targetPort: 8086    # The port inside the container
#      nodePort: 30002      # The port exposed on each node for external access
