apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-notification-api-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/notification-api/*.log
      pos_file /fluentd/log/notification-api.pos
      tag notification-api.log
      <parse>
        @type none
      </parse>
    </source>

    <match notification-api.log>
      @type stdout  # Replace this with your preferred output plugin
      @log_level info
    </match>

#Create this config on node using
#  kubectl apply -f fluentd-gm-user-config.yaml
