apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.appLabel }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.postgres.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.appLabel }}
    spec:
      containers:
        - name: {{ .Values.postgres.containerName }}
          image: "{{ .Values.postgres.image }}"
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
