apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'gm-access-service'
        metrics_path: '/gm-access/api/actuator/prometheus'
        static_configs:
          - targets: ['gm-access-container:8086']

      - job_name: 'gm-user-service'
        metrics_path: '/gm-user/api/actuator/prometheus'
        static_configs:
          - targets: ['gm-user-container:8087']

      - job_name: 'config-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'config-server:8888' ]

      - job_name: 'transaction-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'transaction-api:4000' ]

      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'api-gateway:8080' ]

      - job_name: 'asset-management-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'asset-management-api:4001' ]

      - job_name: 'account-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'account-api:4002' ]

      - job_name: 'discovery-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'discovery-server:8761' ]

      - job_name: 'notification-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'notification-api:8099' ]
