apiVersion: apps/v1
kind: Deployment
metadata:
  name: gm-user-deployment
  labels:
    app: gm-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gm-user-service
  template:
    metadata:
      labels:
        app: gm-user-service
    spec:
      containers:
        - name: gm-user
          image: tobyawo/gm-user-service
          ports:
            - containerPort: 8087
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/gm-user  # Adjust the log path as needed

        - name: fluentd-user
          image: fluentd
          ports:
            - containerPort: 24225
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/gm-user
            - name: fluentd-gm-user-config
              mountPath: /fluentd/etc
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          command: ["fluentd", "-c", "/fluentd/etc/fluent.conf"]

      volumes:
        - name: log-volume
          emptyDir: {}
        - name: fluentd-gm-user-config
          configMap:
            name: fluentd-gm-user-config
