sonarqube:
  extraEnv:
    - name: sonar.web.context
      value: "/sonar"
  extraVolumes:
    - name: sonar-properties-volume
      configMap:
        name: sonar-properties
  extraVolumeMounts:
    - name: sonar-properties-volume
      mountPath: /opt/sonarqube/conf/sonar.properties
      subPath: sonar.properties